fix: change `ValidationError` to `TypeError` in `validate_contained_resource`
Fixes the error 
```
TypeError: ValidationError.__new__() missing 1 required positional argument: 'line_errors'
```
when trying to raise the `ValidationError`.